"""The rule cards: what each part of CAIRN accepts and refuses, and the diagnostic code of each rule.

`CARDS` are the language's. `base`, `integers` and `calls` go with every packet, so no other card repeats what they
say, and the others are selected from the lexical tokens of the source at hand. `TOOL_CARDS` state what the hosts, the
command line and the compiler's own limits refuse; no source selects them, and a refusal names them. A card holds one
paragraph per line and names every code it owns, and `CODES` gives each code exactly one card, so a refusal maps back
to the rule behind it (`card_of`). Shorter wording never grants edit authority.
"""

from __future__ import annotations

import re
from itertools import pairwise
from typing import Any

from ..compiler.cooperative.cooperative import VOTES as COLLECTIVE_VOTES
from ..compiler.primitives.atomics import NAMES as ATOMICS
from ..compiler.syntax.lexing import lex

CARDS = {
    "base": """CAIRN 1.1 is a checked systems language, not Rust or Python. Braces, semicolons, typed signatures, explicit return on every path; no tail expression. fn inc(x:u64)->u64 = add_wrap(x,1); is one return, not a closure. let is immutable, let mut mutable, parameters immutable; no shadowing, no implicit conversion; let x:u32 = 7; annotates.
for i in lo..hi is sequential and half-open, bounds evaluated once, lo first; for i, x in xs is for i in 0..len(xs) with let x = xs[i] (copyable elements); ranges are not lists; only compact/parallel/reduce write for i in n. if/else if/else and while use braces; break/continue target the nearest loop, also from match arms. while/recursion may diverge; no stack bound is proved. Precedence rises || && | ^ & (== != < <= > >=) (+ -) (* / %); && and || stop early. reg/each are old spellings of let mut/for.
No inheritance, overloading, exceptions or hidden allocation; indentation is insignificant. Other features have cards, sent when used. Preserve the fixed task. Typed, tested, SMT-equivalent and Lean-checked are different claims.""",
    "integers": """Types: bool, u8/u16/u32/u64, usize (64-bit), i8/i16/i32/i64. +,-,* and x += e trap on overflow in every build; add_wrap/sub_wrap/mul_wrap are unsigned and modular, so x+1 and add_wrap(x,1) differ at the maximum. /,% trap on zero or signed min/-1; signed remainder truncates toward zero, unlike Python. shl_wrap(x,k), shr(x,k): unsigned x, usize k below the width. &,|,^,~ are unsigned; min/max integer-only. Conversions are explicit calls, u64(x), range checked: narrowing traps outside the target; float to integer truncates toward zero, trapping on NaN or out of range. Literals take the expected type, else u64/f64. const K:u64 = 4 * 1024; folds at compile time. Never weaken arithmetic or the trap/domain policy to pass a check.""",
    "views": """ro<T>[n] and rw<T>[n] borrow host storage; @host is optional, not a transfer. An extent is a literal or an earlier immutable usize parameter; a call omits all or none (E-ARITY): f(xs) is f(len(xs),xs). Indexes are usize and bounds-checked; len(view) reads metadata. Read-only views may alias; an rw view is disjoint from every other view of the call (E-ALIAS). Entry checks cover null/alignment/overflow/overlap numerically; the caller supplies live, initialized, typed storage with no conflicting access. No view returns, resizing, implicit copy or parallelism.""",
    "compact": """let used = compact out for i in n where p yield v; out is an rw borrow or scoped buffer of capacity exactly n (or len(out)); p is bool, v has the element type, and neither may read out or call a writing or allocating function. Selected values fill a stable prefix in order; the tail is unchanged; no allocation or synchronization; the private cursor emits at most once per input. Its arithmetic certificates do not prove the compiler, ownership rules or native backend.""",
    "scan": """let total = scan + out for i in n yield v; writes out[i] = v(0) + ... + v(i) and binds the whole; scan + exclusive out ... writes what came before i, so out[0] is the identity; a scan nobody reads the total of is a statement. The operators are reduce's: add_wrap, mul_wrap, & | ^ min max on integers, checked + on unsigned integers only (it traps exactly when the in-order total overflows), + and * on floats only in a sequential for scan (E-SCAN-OP, E-SCAN-ORDER). out is an rw view or buffer of exactly n elements (E-SCAN-TARGET, E-SCAN-EXTENT); v runs once per i and reads out only at out[i]. scan op parallel runs two passes on the lane pool and gives the in-order answer; over @device views it is CUB's scan, which takes device scratch (gpu_alloc, gpu_free).""",
    "calls": """Call declared functions and listed primitives, never invented libraries; expand an undisclosed function before calling it. A call that writes through a borrow or allocates is a whole statement (f(x); drops a result), initializer or condition, never a nested operand (E-EFFECT-ORDER); one that only releases may nest, since the drop runs where C++ ends the scope. Rows substitute the caller's arguments, recursive calls included. What a callee's interface establishes, and what it leaves to its body, is the packet's evidence.""",
    "floats": """f32/f64 use -ffp-contract=off -fno-fast-math: no reassociation or FMA. Strict flags are not a mechanized IEEE proof. Floating exception flags and NaN payloads are outside the observation model; compiler, runtime and hardware stay trusted.""",
    "math": """sqrt(x) is correctly rounded and floor, ceil, trunc exact, on f32 or f64, alike on every compiler and the device; abs(x) takes a float or a signed integer and traps on the minimum; to_bits(x) is the IEEE pattern as u32 or u64; other arguments are E-MATH-TYPE. exp, log, pow, sin and the like are std.math, libm calls whose last bit varies (row ffi:exp), each bound alone.""",
    "storage": """f16, bf16, f8e4m3 and f8e5m2 are storage floats: they hold and convert, never compute; arithmetic, comparison or a literal of one is E-OPERATOR or E-TYPE-MISMATCH. f32(h) and f64(h) widen exactly; compute there. f16(x) rounds an f32 or f64 once to nearest even as IEEE converts, infinity past the range, and f8e4m3, which has no infinity, traps there; integers and other storage floats go through f32 (E-CAST). quantize[T](x, scale): x / scale rounded once to nearest even and clamped to T's finite range, T a storage float or i8 u8 i16 u16, x and scale f32, scale positive and finite or a trap, NaN kept or a trap for an integer (E-QUANTIZE); quantize_stochastic[T](x, scale, noise:u32) rounds away from zero when the dropped fraction, to 32 bits, exceeds noise. Dequantize is f32(q) * scale. to_bits(h) and from_bits[T](u) move between a float and its pattern. mma_unordered(m, n, k, c, a, b) adds the row-major product of a[m * k] and b[k * n], views of one storage float, into c[m * n], an rw view of f32: exact products, f32 sums in the hardware's order (the receipt says unordered-f32), the written loop on the host and the tensor cores when all three are @device; len must be m * n, m * k and k * n or it traps (E-MMA).""",
    "gradients": """derive grad for f; writes f_grad(f's parameters, seed if f returns a float, d_x per differentiated parameter): reverse mode, adding seed times each partial into d_x:rw<T> or rw<T>[n], reading d_out:ro<T>[n] for each float view f writes, and returning f's result; zero the adjoints first. derive grad[w, b] for f; names the parameters, else every float parameter and ro float view (E-GRAD). Fragment: immutable lets, if whose paths return, reduce + or a let mut float that one for loop adds into (acc += e) and nothing reads until it ends, loops and regions writing out[i] once, + - * /, sqrt, abs, floor ceil trunc, f32/f64 conversions, std.math exp and log, calls of functions with their own derive grad (E-GRAD-FORM, E-GRAD-CALL). A region's lane reading a differentiated input off [i] is E-GRAD-RACE.""",
    "records": """struct Pair {x:u64; y:u64;} is a value record: Pair(a,b), p.x. Only mutable locals and rw borrows change. Fields are any value type, never a borrow, void or the record itself (E-RECORD-TYPE); a record is copyable if its fields are; copying costs work. A Buf field may name an earlier usize field as extent: price:Buf[f64][rows]. Tag-only enum Op {Read; Write;} uses Op.Read and ==. Neither is a dynamic object or allocation.""",
    "generators": """A function may declare one [K:nat] parameter. family gain = scale[1..257]; instantiates gain_1..gain_256 with bounded expansion and no runtime dispatcher. No semicolon follows a function block. Generated entries are not direct edit targets; read the generator's contract. Large expansion is not a measured advantage over compact C++ templates.
derive wire for Packet; takes fixed-width unsigned fields and creates little-endian, declaration-order codecs with no padding; it infers no framing, authentication or validation. wire is a library recipe. recipe name[K:nat, F:fn] for R { ... } (F is a function's name, called as $F(x)) holds ordinary fn and struct declarations and static forms: each f in R { } over fields, or each k in lo..hi { }, at declaration, statement, field-list or call-argument level, where it splices a list ({ a.$f, b.$f } gives two per step). fold | each ... { e } joins the expansions with an operator or a two-operand function (fold add_wrap each ..). where a = offset(f), w = fold + each f in R { bytes(f) } names static values (naturals, min, max); the facts take a field or a type alike, unsigned(f) or bytes(R): bytes bits offset index count typeof unsigned signed integer float scalar record. $name splices into identifiers (encode_$R, value.$f) or stands for the natural or type; bare R is the type; require cond, "message"; states the domain. A generated field may declare an earlier usize field as its extent: $f:Buf[$t][rows];. A recipe may also hold impl Trait for R { ... }.
derive name[naturals] for Type; expands before checking into code of the deriving module, checked like any other. std offers derive eq|ord|hash for P; (impls of std.core's Eq, Ord and Hash).""",
    "memory": """buffer scratch:u64[n] = zeroed; explicitly allocates zeroed heap storage; stack scratch:u64[32] = zeroed; explicitly reserves zeroed stack storage. Elements are non-linear values (E-LINEAR-STORAGE). Stack capacity is a literal; a function's stack declarations total at most 65536 bytes (E-STACK-LIMIT), not a bound on recursion, spills or native stack. Bind computed heap capacity to an immutable usize first (E-OWNER-EXTENT). The array is neither copyable nor returnable; lend it to helpers. len(scratch) is metadata; elements are writable without mut. Buf[u64](n) is the same array as a movable owner. Release is at normal scope exit, return, break and continue. Allocation failure and guards abort, promising no cleanup. No manual free or escaping borrow. Receipts expose alloc/free/zero_init and private reads/writes.""",
    "sums": """enum Parsed {Ok(Header); Short(usize); Empty;} is a tagged sum, enum Result[T, E] {Ok(T); Err(E);} a generic one; payloads are any value type. Parsed.Short(n) may be written Short(n) where the sum is expected (return, typed let, assignment, argument, ==), unless a local, constant, function or type has that name (E-VARIANT-AMBIGUOUS). match p { Ok(h)=>return h.size; Short(n)=>return 0; Empty=>{ n = 0; } } has exactly one arm per variant, no wildcard (E-MATCH-COVERAGE); an arm names a variant of the subject and is a block or one return, break, continue, assignment or call; binders are fresh, immutable, local to the arm; the subject is evaluated once; matching an owner consumes it. A sum is copyable if its payloads are; no heap allocation, no unchecked payload access. try x on a two-variant sum (success first) yields the success payload or returns the failure from the enclosing function, whose return type is a two-variant sum with the same failure payload (E-TRY). It is the only propagation form; nothing unwraps implicitly, and f(x); may not drop such a sum (E-DISCARD): try f(x); or let _ = f(x);. Err(_) and for _ bind nothing; a linear payload is never _ (E-LINEAR-LEAK). Foreign callers must supply a valid tag and its initialized payload.""",
    "generics": """fn largest[T](a:T, b:T) -> T and struct Pair[T] { a:T; b:T; } take type parameters; [K:nat] is a static natural. Instances are monomorphized on demand and each is checked as ordinary code; type arguments are inferred from values, literals and the expected type, or written f[u64](x), Pair[u8](1, 2), Option[u64].None.
trait Shape { fn area(self:ro<Self>) -> u64; } with impl Shape for Square { ... } dispatches statically on the Self argument, and [S:Shape] is checked when the instance is made. Bounds join with +: a trait, a kind (copy: reusable; affine: droppable and storable; none: may be linear) or a scalar class (integer unsigned signed float numeric scalar: operators and literals allowed). value.f(a) is f(value, a), found first in the module of the receiver's type; Trait.f(value) picks between two traits' f (E-TRAIT-AMBIGUOUS). A ro<T> or rw<T> parameter borrows the named place you pass (a local, a field, another borrow): write area(sq), never &sq, and rw needs a mutable place. There is no implicit boxing.""",
    "owners": """let mut b = Buf[u64](n); is a first-class zeroed heap array, and Array[u64, 4]() an inline one. Owners are affine: binding, passing by value or returning one moves it, and the old name is dead (E-MOVED). An owner never moves out of a place or a borrow (E-PARTIAL-MOVE, E-MOVE-BORROW): take(place) moves it out and leaves zero, swap(a, b) exchanges two places, and let Conn(sock, sent) = c; consumes a whole record and binds every field, the way out for a linear field. An outer owner cannot move inside a loop, closure or lane (E-MOVE-IN-LOOP).
A linear struct value is consumed exactly once on every path (E-LINEAR-LEAK, E-LINEAR-BRANCH); defer call(x); schedules that one visible call for every normal exit of its block. ro<T> and rw<T> borrow one value and read and assign like it; x[lo..hi] passes a part of an array with one dynamic guard, and two parts are disjoint only if they visibly share a boundary.
Letting an owner go charges free where the release is: the end of the block or match arm holding it, a return that leaves while it is held, a function handed one that passes it on to nobody, and the place a new value is assigned over. A linear value need not own storage, so consuming one charges nothing on its own.
In struct Chart { rows:usize; price:Buf[f64][rows]; } the extent is an earlier usize field of the record (E-EXTENT), and len(c.price) == c.rows then holds of every value, so total(c.rows, c.price) passes the field whole with no part guard. Nothing checks it at run time, so Chart(n, Buf[f64](n)) writes the Buf inline on the same n as rows, and neither half is assigned, taken, swapped or lent rw alone (E-EXTENT-FIELD). Moving, take, swap and zeroed storage carry the record whole and keep it.""",
    "assembly": """asm x86_64 "bswapq %0" (out r:u64 = x); is typed assembly, inside unsafe { }. The target is ptx with the architecture it needs (asm ptx sm_75 ...), run only in a kernel fn or a lane of a region that indexes an @device view, or x86_64 or aarch64, run only in host code and built only on a host of that family (E-ASM-TARGET). Operands are numbered as written, outputs first, and the template names every one as %0, %1, with %% a literal % (E-ASM-OPERANDS). The type decides the register: host integers r, host floats x or w; PTX u16/i16 h, u32/i32 r, u64/i64/usize l, f32 f, f64 d; bool, storage floats, records and PTX u8 have none (E-ASM-CONSTRAINT). out name:T binds a fresh local after the statement, out name:T = e starts it at e. A view or local array input passes its address and needs effects(read:xs) or effects(write:xs), which lends it like a call (E-ASM-EFFECT); effects may also name fence barrier atomic io mmio, trusted as written, and any of them makes it volatile with a memory clobber. clobbers(rax, rdx) names host registers written besides the outputs (E-ASM-CLOBBER); asm volatile keeps a clock read from being merged. The row gets asm:TARGET and the declared effects, so bind each call to a let (E-EFFECT-ORDER). In device code PTX declares only reads, writes and fence (E-ASM-LANE), and an address is a whole-array access for the lane rule (E-PARALLEL-RACE). For more than an instruction or two, or a design CAIRN cannot say, a foreign implementation in CUDA or C++ (the foreign card) keeps the design and is validated against its reference.""",
    "foreign": """A foreign implementation is vendored C++ or CUDA standing for a CAIRN reference. The manifest's [foreign] table names each source and the symbols it defines, "vendor/stencil.cu" = ["stencil_1d_tiled"]; an extern gives each its signature and effects; and fn stencil_tiled(...) implements stencil_1d { unsafe { stencil_launch(n, out, x); } } is the implementation, whose reference's ceiling names the foreign effect (E-IMPL-EFFECT). extern "stencil_1d_tiled" fn stencil_launch(n:usize, out:rw<f32>[n]@device, x:ro<f32>[n]@device) launch(n, 256) effects(); is a CUDA __global__ kernel: a host call launches it over n threads, 256 to a block, on the thread's stream and returns once it has run; it takes scalars and @device or @unified views, returns nothing, and a block is 32 to 1024 threads in whole warps (E-LAUNCH, E-PLACEMENT); its row adds par:device and trap. The build compiles each source unchanged with the program's flags and device target and asserts each extern's C++ types; a C++ symbol has C linkage. cairn foreign PATH --implementation F says what F has, each claim apart: a declared contract, trusted and not checked; native-built; device-inspected (registers, shared memory); validated against its reference, or not run when it runs device code.""",
    "effects": """Every function has an inferred effect row; pure and effects(read:x, trap) after the return type are checked ceilings, never wishes (E-EFFECT-CEILING). extern fn write(fd:i32, data:ro<u8>[n], n:usize) -> i64 effects(io); declares a C symbol whose effects are mandatory because its body is invisible, and ffi:write then appears in every transitive caller. alloc is charged where storage is taken and free where it goes back, so fn sink(b:Buf[u64]) {} has the row free, and a ceiling that leaves free out is refused.
Foreign calls, mmio_read[u32](addr), mmio_write[u32](addr, v) and asm("wfi") are legal only inside unsafe { }. Do not widen a ceiling or add unsafe to make an edit pass.""",
    "parallel": """parallel i in n { out[i] = a * x[i] + y[i]; } runs one lane per index and finishes before the next statement. Placement is part of a view type: @host (the default), @pinned, @unified, @device. Indexing a @device view makes the region CUDA lanes, otherwise host threads; host code cannot index @device memory and lanes cannot index the other side; a @pinned or @unified view may be passed where @host is asked, and @unified also as @device. The first host region of a process creates the lane pool and later ones reuse it; a small one is just the loop.
Whatever any lane writes may be touched only at [i], or only in lane b's own block: out[b * S + j] with j < S for one constant S, or an index a loop or condition keeps in [b * S, b * S + S), which a helper may write when the lane lends it that part; any other access to it is E-PARALLEL-RACE. Shared scalars cannot be assigned: use let s = reduce add_wrap for i in n yield x[i];, which is also the ordinary fold outside any region, where i runs over 0..n and the operator is one of add_wrap mul_wrap min max & | ^, or + * on floats. reduce op parallel i in n yield e folds the same integers on the lane pool, in blocks n alone fixes, to the in-order answer; floats there are E-REDUCE-ORDER. plan f { grain 1; lanes 8; } picks how f's host regions are split over the pool, and plan f { block 128; per_lane 4; unroll 4; vector 4; } how its device regions launch, vector W moving each array a lane touches only at [i] W elements at a time (a power of two, at most 16 bytes), stage R loading once per block into shared memory an array the lanes only read at [i + d] with |d| <= R; plan f { fuse 2; } runs adjacent regions over one extent as one traversal when every array they share is touched only at [i] and no body can trap, a local buffer only they touch at [i] then lives in each lane, never in memory, and a host reduce over the same extent may end the chain, folding in its own order; no plan changes a result (E-PLAN: an item out of range, a region f lacks, or nothing fuse may join).
Lanes cannot return, nest or move outer owners, and neither a lane nor anything it calls may do I/O, spawn, touch the machine or, on the device, allocate or use strings and host owners. A lane may call a fn parameter f of its function (effect lane:f): whoever finally passes a closure must not write what it captures. kernel fn at(...) -> f32 is a device helper: it may index @device views, is callable only from device lanes and other kernels, and cannot allocate, do I/O or start regions. buffer d:f32[n]@device = zeroed; is a scoped device owner; transfer(dst, src) is the only way across placements. reduce on the device combines in an unspecified order: exact for add_wrap mul_wrap & | ^ min max, not for float + and *; reduce + is checked on unsigned integers, not offered on signed. A function whose row has no host transfer, device allocation (buffer, device reduce, scan or compact), spawn or wait, I/O, foreign call, machine register, host assembly, function value, atomic, lock or @unified view waits once when it returns, not after each region, and its library header adds cq_NAME(stream, ...), which queues the work on the caller's stream and returns without waiting (E-ENQUEUE in the header says why a function has none). cairn build, run, test and validate with --emulate run device work on host threads, judged against the device target: for correctness, never for timing, and a validation so run is finite-tested-emulated, which cairn tune chooses on only with --accept-emulated; typed PTX, a launch(...) kernel, vendored CUDA or a device feature the host does not model is E-EMULATE. When lanes cannot say the design you want, such as another launch or memory access, keep that design: write the function in CUDA or C++ as a foreign implementation (the foreign card), which cairn validate holds to the reference, rather than a narrower region.""",
    "wide": """let v = load_wide[4](x, i); reads x[i..i + 4] as one Array[f32, 4] and store_wide(out, i, v); writes one back, each a single access on the device (LDG.E.128). K is a constant power of two and K elements of a scalar or storage float fill at most 16 bytes: 4 f32, 8 f16, 2 f64, 16 u8 (E-WIDE); store_wide takes an Array of the array's own element type. Both trap unless i + K <= len(x) and x[i] sits on K * sizeof(T) bytes, which a view the caller passes need not. A third or fourth argument hints the device's caches by name: Cache.all (default), Cache.l2 (.cg), Cache.streaming (.cs), Cache.last_use (.lu, loads only), Cache.read_only (.nc, like __ldg, loads of an ro @device view only); shared arrays take no hint, and the host does K plain accesses and ignores it (E-WIDE). Every rule sees the part x[i..i + K]: in parallel i in m a lane may store out[4 * i..4 * i + 4] (E-PARALLEL-RACE otherwise), and the phase and global rules count all K elements. cairn explain lists each access with its width.""",
    "atomics": """atomic_add_wrap(bins[k], 1); updates one element of an array in one indivisible step and returns its old value, from host code, any lane or any cooperative thread, host or device: atomic_add_wrap (u32 u64 usize, modular as add_wrap: an atomic add cannot check overflow), atomic_min, atomic_max and atomic_cas(x[i], expected, desired) (u32 i32 u64 i64 usize; cas stores desired where x[i] held expected and returns the old value either way), atomic_and, atomic_or, atomic_xor (u32 u64 usize), atomic_add_unordered (f32 f64: adds rounded in the order threads arrive, an f32 add flushing subnormals on the device; the receipt states the bound). The first argument is the element x[i], written in place, of a writable array (E-ATOMIC). Updates are relaxed and race no other update, so any lane may update any element; an array a region updates atomically is not read or written plainly in it (E-ATOMIC-MIXED): anywhere in a parallel region, anywhere in a cooperative region for an outside array, between barriers for a shared one. Read results after the region, after a barrier, or in the region's finish. The old value differs by thread: a barrier under a condition on it is E-COOP-BARRIER. Row: atomic, write:x; nested in an expression it is E-EFFECT-ORDER, so bind it: let old = atomic_max(best[0], v);""",
    "cooperative": """blocks b in g threads t in 256 { ... } runs g blocks of 256 threads, b and t usize; up to three names a side, fastest first (blocks bx, by in gx, gy threads tx, ty in 32, 8: thread tx + 32 * ty). Thread extents are literals or constants, whole warps, 32 to 1024 in all (E-COOP-SHAPE). shared tile:f32[1056] = zeroed; declares directly in the body one array per block, zeroed where each block starts, 48 KiB in all (E-COOP-SHARED); shared warps:f32[8]; is not zeroed, and every element a thread reads (or updates atomically) must be written first, by it or by any thread before a barrier, on every path (E-COOP-UNWRITTEN). barrier; waits for every thread of the block: never under a condition on a thread name, nor in a loop with break or continue (E-COOP-BARRIER). A local assigned from t, lent rw to a call, written through an element or assigned by a closure differs between threads, as does what an atomic or typed asm returns, and the right side of && or || runs only where the left lets it. Runs on the device when a view it indexes is @device, else on host threads; its row gains par:device or par:host and zero_init. blocks b in g threads t in 256 { ... } then threads t in 256 { ... } adds a finish: one block of the region's thread count (E-COOP-SHAPE), run once after every block has finished, even for g = 0, that may read anything the blocks wrote, plainly or atomically; no block name or block local is in scope, and it declares its own shared arrays; on the device it is still one launch. A feature devices.md's table of what fast kernels use marks foreign (dynamic shared memory past 48 KiB, warp match, clusters, TMA, wgmma, grid-wide sync, graphs) is written as a foreign CUDA implementation of the CAIRN reference, which cairn foreign inspects and cairn validate holds to it; never settle for a narrower kernel.
Between two barriers no two threads touch one element of a shared array where either writes: two writes E-COOP-CONFLICT, a read of what another thread wrote earlier in the phase E-COOP-UNORDERED (a barrier between them fixes it), a write over what another may still be reading E-COOP-REUSE, an index read from data or differing by a run-time value beside a write E-COOP-UNDECIDED. An array from outside: each element written by one thread of one block, at an index like b * 256 + t or (bx * 32 + r) * h + by * 32 + tx, and read only by the thread that writes it (E-COOP-GLOBAL); guard a single writer with if t == 0. A closure in the body names no shared array, pipeline or outside array (E-COOP-UNDECIDED).
shuffle(v, lane), shuffle_xor(v, mask), shuffle_down(v, delta), shuffle_up(v, delta) and let s = reduce + warp yield v; (reduce's operators, a fixed butterfly order) need whole warps: only under conditions warps agree on, t < 32, t / 32 == w, ty < 4 when tx counts 32 (E-COOP-WARP); so do the votes, one instruction each: warp_ballot(c) (u32, bit l for lane l), warp_any(c), warp_all(c), the same in every thread of the warp, and warp_match(v) (the lanes whose v has this lane's bits; 32- and 64-bit integers and floats). A thread obeys the lane rules: no outer scalar writes, I/O or nested regions.
pipeline p:u64[256] depth 2; declares 2 stages of 256 u64 (u32 i32 f32 u64 i64 f64) in the block's shared memory. p.fill(x, start, count) starts copying x[start..start+count] into the next free stage, zeros past count; p.wait() is a barrier after which the oldest stage in flight reads as p[i]; p.release() ends its readers, and the next barrier frees the stage. All three need the whole block (E-COOP-BARRIER). Reading, releasing or waiting with no stage in the needed state is E-STAGE-UNREADY; a fill with no free stage, or a wait while a stage is still readable, is E-STAGE-BUSY (put a barrier after release before the next fill); a loop or if that leaves a pipeline in another state than it found it is E-STAGE-LOOP: fill depth - 1 stages first, then fill, wait, read, release, barrier each iteration, with no break or continue. Any use of p but as the receiver of its operations reads the readable stage; fill copies from an outside array where the region runs (E-PLACEMENT). Depth changes shared bytes and how many copies a wait leaves in flight, nothing else. When a block cannot say the kernel you want, keep that kernel: write it in CUDA as a foreign implementation of the function (the foreign card), which cairn foreign inspects and cairn validate holds to the reference, rather than a narrower one.""",
    "tasks": """let t = spawn f(args); runs a declared function on its own thread and gives a linear ticket that wait(t) must consume in the same function; let r = wait(t); is f's result, and wait(t); alone serves when f returns nothing. Until then every place lent to the task is leased (E-LEASED): nobody writes what it reads or touches what it writes, and visibly disjoint parts (d[0..mid], d[mid..n]) may be lent mutably to different tasks. What is leased is the place lent, not the local it sits in: two fields of one record (spawn f(box.a) beside spawn g(box.b)) go to two tasks, and len(box.a) still reads while box.a's elements are lent, while lending the record whole leases every field in it, and box.a = Buf[u64](2) under a lease of box.a is refused.
let g = Group[u64](4); holds up to 4 tasks at once: spawn f(args) into g; hands the task to g with no ticket, let r = collect(g); is the result of whichever task finishes next (an empty or a full g traps), and wait(g); joins the rest and drops their results. Every place lent to any task of g, on any path, is leased until wait(g); collect returns none, so a loop lends g only ro places.
Atomic[u64] and Mutex[T] are declared in place and shared by ro borrow: a.fetch_add(1, Order.relaxed) always names its memory order, and m.with(|s:rw<T>| { ... }) is the only way into a mutex. Tickets, groups, atomics and mutexes are never stored, passed by value or returned.
Device work can be queued: let up = spawn transfer(x, a); let k = spawn parallel i in n after up { y[i] = x[i]; }; each returns at once with a linear ticket that leases the views it touches until wait; after orders it behind live tickets on the device and lets it share what they hold. Only device regions and transfers are queued.""",
    "rings": """let mut q = IoRing(n); declares, in place, a kernel ring of up to n operations in flight with no thread each. q.read(fd, data, count, offset, tag), q.write(...), q.recv(fd, data, count, tag), q.send(...) and q.accept(fd, tag) move the Buf[u8] data into the ring: it is dead until let data = q.next(tag, result); hands the next finished one back with its tag and the kernel's result (a count, a descriptor or -errno; io.outcome(result) makes it a Result). wait(q), or defer wait(q), consumes the ring where it was declared, after every operation finishes. A ring may be lent rw to a callee or a task, never stored, passed by value or returned (E-PINNED). Every submission returns through next exactly once, with -errno if the kernel refused it; a ring the kernel would not set up is down, q.status() is that -errno, and each submission comes straight back with it. Submitting when q.room() == 0, or next when q.pending() == 0, traps. q.timeout(ns, tag) finishes with -ETIME after ns; q.cancel(tag) stops what runs under tag, which still returns through next with -ECANCELED or its own result. Host only; effects io, alloc, free.""",
    "closures": """fn(u64) -> u64 is a copyable code pointer to a plain declared function of values. ro<fn(u64) -> u64> is a borrowed callable: pass a declared function or write the closure in place, apply(n, xs, |x:u64| -> u64 { return x + bias; }). A closure captures its scope by reference, exists only as that argument, never allocates, and its effects belong to the function that wrote it. What it captures it borrows for that call (rw where it writes), so the same call cannot lend, move or write those places.
ro<dyn Shape> and rw<dyn Shape> parameters take any named place whose type implements the trait; calls through them add the dispatch effect and the effects of every implementation. Dynamic references are never values; Dyn[Shape](value) is the owned form, an affine heap value (alloc, free) that dispatches and lends itself as dyn.""",
    "tests": """test sums { let s = total(3); assert(s == 6, "three"); } is a test: no parameters, no result, one name per module (E-TEST), checked like a void function with any effects. No other build holds a test and nothing can call one (E-CALLEE). cairn test runs every test block, each in a process of its own, beside the project's JSON contracts; a test passes only when its process exits 0, so a failed assert or guard, a signal or a timeout fails that test alone. assert(cond) or assert(cond, "why") traps when cond is false, naming its file and line; the condition is a bool and the text one literal (E-ARITY). assert_eq(a, b) also prints both scalars when they differ (E-ASSERT-EQ otherwise). A call that allocates or writes is bound before the assert that reads it (E-EFFECT-ORDER).""",
    "implementations": """fn total_by4(n:usize, xs:ro<u64>[n]) -> u64 implements total when n % 4 == 0 { ... } is a separately written implementation of the reference total: exactly its parameters, types, extents, placements and result (E-IMPL-SIGNATURE), declared in total's module, not generic over types, not a kernel, and never an implementation of an implementation (E-IMPLEMENTS). Its row stays inside total's declared ceiling, or inside total's own row when total declares none (E-IMPL-EFFECT: a while loop adds diverge, a Buf alloc, a parallel region par:host), and it writes no rounding total does not write (E-IMPL-NUMERICS).
when is optional and cannot trap: comparisons, && || !, & | ^ ~, min, max, the wrapping forms, / or % by a nonzero literal or natural parameter and len of a view parameter, over value parameters, literals, constants and natural parameters (E-IMPL-WHEN). Where it is false the reference runs, so the input domain stays the reference's. needs(cp_async) names the device features its device code uses (E-IMPLEMENTS for any other name, or for an implementation that runs no device code).
plan total use total_by4; is the only way it runs: total's body then starts by testing the condition and calling total_by4, and a call such as total(8, xs), whose arguments decide the condition, calls total_by4 directly, unless the condition computes with a float (E-IMPL-USE for a name that is not total's implementation, or a second selection; E-IMPL-TARGET when the build's device target lacks a feature the selected implementation needs). Without a plan the reference runs. Only a test block calls an implementation by name, and an implementation never reaches its reference, directly or through another reference's implementation (E-IMPL-CALL). total's row joins every implementation's, so a selection changes no row. Do not change the reference, the signature or the ceiling to admit an implementation.
fn total_by[K:nat](n:usize, xs:ro<u64>[n]) -> u64 implements total when n % K == 0 tune K in [2, 4, 8] { ... } exposes K to the search: each value tune lists is an instance, total_by[4], with K a usize constant in its body and condition, held to every rule above whether or not a plan selects it; one that breaks a rule is refused with that rule's code and named. tune K in [2, 4], W in [1, 3] lists two naturals, at most 16 instances in all. plan total use total_by[4]; selects one; cairn tune tries every instance, and cairn validate --symbol total_by[4] validates one, since the condition and the tiles change with K. E-IMPL-PARAM: a natural with no values, tune without a natural, a value tune does not list, or a selection without values.
An implementation may also be vendored CUDA or C++, a foreign implementation (the foreign card): when CAIRN cannot say the design an implementation needs, write it there and validate it rather than settle for a narrower one.""",
    "printing": """println("n = ", n, ' ', ok); writes each argument in turn: an integer in decimal (-1 alone is an i64), a bool as true/false, a character literal as its byte, a float in its shortest round-trip form, or the bytes of a string, u8 view, part, Buf, Array or Vec[u8]; anything else is E-PRINT-ARG, so format it with std.fmt or print its fields. print, println, eprint, eprintln: stdout or stderr, no allocation; format(v, ...) appends to a Vec[u8] (E-FORMAT-TARGET) and may grow it. Every argument is computed, left to right, before a byte is written. Not in a lane (E-PLACEMENT, E-PARALLEL-CALL); a program's own print wins.""",
    "layouts": """layout T = pad(rows(32, 32), 1); declares a compile-time storage layout: rows(R, C), cols(R, C), strided(R, C, SR, SC), pad(L, P) (the larger stride grows by P), swizzle(L, B, M, S) (CuTe's Swizzle<B, M, S>), transpose(L), tile(L, TR, TC) (coordinates i, j, r, c), inverse(D) (INV.row(r, c) is the participant holding element (r, c), INV.col(r, c) its value). layout D = spread(T, TR, TC, VR, VC); gives TR x TC participants, row by row, a VR x VC block of T each, repeated down and across T. In code T.at(r, c) is an element's offset, D.row(t, v) and D.col(t, v) participant t's value v, D.at(t, v) its offset in D's tile, each argument trapping outside its extent; T.cosize(), T.size(), T.extent(k), D.participants() and D.values() are constants. Every storage layout gives each element its own offset and every spread gives each element exactly one holder (E-LAYOUT-OVERLAP, E-LAYOUT-GAP); L.at(D.row(t, v), D.col(t, v)) needs L and D's tile of one shape (E-LAYOUT-CONSUMER); every offset stays below 2^63 - 1 and a swizzle's B + M + S at most 63; anything else malformed is E-LAYOUT. The receipt's layouts and cairn explain give coverage, runs (adjacent values one access moves) and bank_ways (shared-memory conflicts).""",
    "fragments": """A tensor-core fragment is one warp's A, B or accumulator: WmmaA[T, M, N, K], WmmaB, WmmaAcc (nvcuda::wmma: 16,16,16 or 32,8,16 or 8,32,16) and MmaA, MmaB, MmaAcc (PTX mma.sync: 16,8,16); T is f16 or bf16 for A and B and f32 for the accumulator (E-FRAGMENT); TmemAcc needs tcgen05, which sm_120 lacks, and is refused (E-TARGET-FEATURE). let mut acc = WmmaAcc[f32, 16, 16, 16](0.0); fills one; mma_load[WmmaA[f16, 16, 16, 16]](tile, L, i, j) reads fragment (i, j) of a shared array or device view laid out by the layout L, counting whole fragments; mma_store(tile, L, i, j, acc) writes an accumulator back; acc = mma_unordered(acc, a, b) adds a * b, its K sums in f32 in the hardware's order (receipt: unordered-f32). mma_get(acc, v) and acc = mma_set(acc, v, x) reach value v of an MmaAcc that this thread's lane holds, element (l / 4 + 8 * (v / 2), 2 * (l % 4) + v % 2) of lane l, the layout spread(rows(16, 8), 8, 4, 1, 2); a WmmaAcc has no defined share (E-FRAGMENT). Each is a warp operation: only inside blocks ... threads ... { }, reached by whole warps, its coordinates, fill value, A, B and a WmmaAcc the same in every thread of a warp (t / 32 is; t is not) (E-FRAGMENT, E-COOP-WARP). A WMMA store names no lane, so a barrier comes between it and any thread's access to what it wrote. WMMA needs an unswizzled row-major layout with rows a multiple of 16 bytes apart, mma.sync from shared memory rows whose 16-byte runs stay together (E-LAYOUT-CONSUMER). The build's device target must provide wmma or mma_sync, and bf16 for bf16.""",
    "lends": """struct Vec[T] { data:Buf[T]; len:usize; lends data[0..len]; } lends that part: named where a view is expected, v is v.data[0..v.len], guarded and leased as written, and for x in v walks it. Bounds are literals or usize fields (E-LENDS).""",
    "modules": """module net.http; names the module of what follows, and pub exports. import net.http; allows http.get(...); import a.b as c; renames; import std.core (Option, Result); also brings those names in unqualified. std.* ships with the compiler and nothing is downloaded. A private name of another module is not callable (E-PRIVATE): request context instead of guessing.""",
}

TOOL_CARDS = {
    "hosts": """An agent edits through a host that holds the program, sends a packet and admits or refuses each reply; cairn mcp serves the same hosts. A request is JSON of the protocol its packet names, with exactly its fields and kinds (E-REQUEST). A handle, digest or state the host did not send, a spent session, or one whose source, files or toolchain moved on is E-SESSION: ask again or open a new session, never guess. A symbol names exactly one authored function, with its module when two modules declare the name (E-SYMBOL); a site is one the packet lists (E-SITE); a template is not edited (E-EDIT-PROFILE); the host's own contract, evidence and allowed effects are well formed or E-CONTRACT.
The host splices a reply into the pinned original and rechecks the whole program. It refuses a changed signature (E-SIGNATURE), a declaration added, removed or hidden behind a trailing comment (E-DECLARATION), an effect beyond the ceiling (E-EFFECT-EXPANSION) or new in a caller's row (E-CALLER-EFFECT), a call of a function the packet did not show (E-CONTEXT-CLOSURE: expand it first), and under preserve a change of behaviour or of code (E-PRESERVE, with an input where it differs when there is one). The signature, the ceiling and the contract are the host's; change the body.""",
    "migrations": """cairn migrate PATH --symbol f --to SIGNATURE authorizes one interface change, --also NAME=SIGNATURE others with it and --allow EFFECT what rows may gain. The packet shows every function the migration may rewrite. A reply maps each function it rewrites to its whole new declaration: an authorized function (E-MIGRATION-SCOPE) with its own name and visibility, in the project's own files, at most 64 functions (E-MIGRATION), with the authorized signature (E-SIGNATURE), no declaration added or removed (E-DECLARATION) and no effect the host did not allow (E-CALLER-EFFECT). The whole program is rechecked, and every file is written or none.""",
    "sketches": """A host may ask for named expressions instead of a body. The reply is one JSON object that maps every slot to one expression string, with no other key, no comment in a value, 64000 bytes of choices and 128000 of reply at most (E-SKETCH-CHOICES). A sketch has 1 to 16 descriptive slot names (E-SKETCH-EMPTY, E-SKETCH-NAME), each on exactly one expression and none inside another (E-SKETCH-SITE, E-SKETCH-OVERLAP), and its slots are fixed once it is sent (E-SKETCH-SEALED). A semantic check needs a fixed reference of the same function (E-SKETCH-CONTRACT), and a search tries 1 to 4096 candidates within its budget (E-SKETCH-BUDGET).""",
    "validation": """An implementation session pins its reference, the tolerance, the test policy and the permitted inputs. A submission is one implementation of that reference, new or replacing one of the same name, with the helpers it calls and nothing else (E-DECLARATION); it never redefines the reference or implements another function (E-REFERENCE), and names no tolerance (E-TOLERANCE), cases, seed, budget, policy or test block (E-TEST-POLICY), and no domain, inputs or precondition (E-DOMAIN): narrow where it applies with when instead. The host rechecks the program under every rule of the implementations card and validates the submission against the reference under the pinned policy; a failing or undecided validation is E-VALIDATION, with the shrunk input when one failed. Fix the algorithm for every input its condition admits, not for that one.""",
    "commands": """cairn prints a JSON record when piped and text at a terminal. E-PROJECT-OR-ENVIRONMENT, status unknown, says what a manifest, a path, an option or a tool of this machine lacks; it is no verdict on the program. A device target is sm_ and a compute capability with an optional f or a suffix, sm_120, from --device-target, [build] device_target or the one kind of GPU present (E-TARGET); what needs a feature the target lacks is E-TARGET-FEATURE, a record made for another target E-TARGET-MISMATCH, and a build needs an nvcc that compiles the target (E-TARGET-TOOLKIT). cairn predict and cairn tune --card name one packaged device card by its key or the start of one before a hyphen, as cairn cards lists them (E-DEVICE-CARD). build, run and test check an export first: a directory that is none is E-EXPORT, a changed, added or removed file or an edited record E-EXPORT-TAMPERED, another compiler E-EXPORT-TOOLCHAIN. cairn rules takes a diagnostic code, a card's name or a source path, else E-RULE.""",
    "harness": """cairn export PATH --harness sol-execbench|gpumode|kernelbench --symbol f --out DIR packages f as a benchmark submission beside its export and a cairn.harness/1 record, and runs, submits and fetches nothing: it prints the commands that would, and popcorn's --mode leaderboard is a public ranked submission. harness.toml beside the manifest, or --mapping, is data: each [[argument]] in the order the benchmark passes it, with name, parameter, dtype (bfloat16 or bf16) and shape (axis names or integers, none for a Python number) and output = true for a destination the benchmark allocated; each [[result]] a tensor the adapter allocates and returns; [axes] the fixed axes; [extents] each usize parameter no argument feeds, as + - * / over axes; [benchmark] definition, leaderboard, gpu and problem. A parameter fed twice or by nothing, an axis no shape names or an input CAIRN writes is E-HARNESS-MAPPING; a dtype that is not the parameter's element type, or a format CAIRN has no type for such as NVFP4, E-HARNESS-DTYPE; a function with no C entry E-HARNESS-SYMBOL; a result for SOL-ExecBench, an output argument for KernelBench, a returned value or a solution naming no definition E-HARNESS-FORMAT. The binding checks every tensor before a pointer crosses and queues device work on torch's current stream. cairn new DIR --from-sol-execbench definition.json writes the reference's signature, harness.toml and the tightest workload tolerance as policy.json. SOL-ExecBench scores 0.5 at its PyTorch baseline and 1.0 at its modelled speed of light, which is not a utilization.""",
    "limits": """The compiler bounds its own work: 16000000 bytes of source (E-SOURCE-LIMIT), expressions nested 100 deep (E-DEPTH), 200000 expression visits while checking (E-AST-LIMIT), 32768 functions and 3200000 syntax nodes after expansion, 2048 copies from one recipe or from all families (E-EXPANSION-LIMIT), and a finite effect fixed point (E-EFFECT-LIMIT); split the program or the expression. E-INTERNAL and E-PROJECTION are faults of the compiler, never of the program: report them with the program. E-RESOURCE-OR-IO says the compiler could not read or hold its input, and establishes nothing about the program.""",
}

CORE = ("base", "integers", "calls")  # sent with every packet
CODES = {
    "base": "E-PARSE E-LEX E-NAME E-RETURN E-UNREACHABLE E-EXPRESSION-BODY E-IMMUTABLE E-LVALUE E-UNBOUND E-SHADOW "
    "E-DUPLICATE E-PARAM E-BUILTIN-NAME E-TYPE E-TYPE-MISMATCH E-ELEMENT-LOOP E-LOOP-CONTROL",
    "integers": "E-WRAP-TYPE E-OPERATOR E-MINMAX E-CAST E-LITERAL-RANGE E-CONST",
    "calls": "E-CALLEE E-CALL E-ARITY E-EFFECT-ORDER E-DISCARD",
    "views": "E-EXTENT E-CALL-SHAPE E-CALL-VIEW E-VIEW-ALIAS E-INDEX E-LEN E-WRITE-LEASE E-ALIAS E-ESCAPE",
    "compact": "E-COLLECT-BINDING E-COLLECT-CAPACITY E-COLLECT-SELF-READ",
    "scan": "E-SCAN-OP E-SCAN-ORDER E-SCAN-TARGET E-SCAN-EXTENT",
    "floats": "",
    "math": "E-MATH-TYPE",
    "storage": "E-QUANTIZE E-MMA",
    "gradients": "E-GRAD E-GRAD-FORM E-GRAD-CALL E-GRAD-RACE",
    "records": "E-RECORD E-FIELD E-RECORD-TYPE E-ALIGN E-ENUM",
    "generators": "E-FAMILY-TARGET E-FAMILY-LIMIT E-UNINSTANTIATED E-DERIVE-FIELD E-RECIPE E-RECIPE-STATIC "
    "E-DERIVE-DOMAIN E-DERIVE-RECIPE E-DERIVE-TYPE E-DERIVE-COLLISION",
    "memory": "E-OWNER-ELEMENT E-STACK-EXTENT E-STACK-LIMIT E-OWNER-EXTENT",
    "sums": "E-SUM-PAYLOAD E-SUM-ARITY E-VARIANT-AMBIGUOUS E-ENUM-VARIANT E-MATCH-TYPE E-MATCH-COVERAGE "
    "E-MATCH-DUPLICATE E-MATCH-BINDING E-TRY",
    "generics": "E-STATIC E-INFER E-GENERIC-ARITY E-GENERIC-KIND E-TRAIT-IMPL E-TRAIT-OVERLAP E-BOUND E-TRAIT-AMBIGUOUS",
    "owners": "E-MOVED E-PARTIAL-MOVE E-MOVE-BORROW E-UNPACK E-MOVE-IN-LOOP E-LINEAR-LEAK E-LINEAR-BRANCH "
    "E-LINEAR-STORAGE E-DEFER E-EXTENT-FIELD",
    "assembly": "E-ASM-TARGET E-ASM-OPERANDS E-ASM-CONSTRAINT E-ASM-EFFECT E-ASM-CLOBBER E-ASM-LANE",
    "foreign": "E-LAUNCH E-FOREIGN",
    "effects": "E-EFFECT-CEILING E-EXTERN E-EXTERN-EFFECTS E-UNSAFE",
    "parallel": "E-PLACE E-PLACEMENT E-PARALLEL-RACE E-PARALLEL-WRITE E-REDUCE-OP E-REDUCE-ORDER E-PLAN E-EMULATE E-ENQUEUE "
    "E-PARALLEL-CONTROL E-PARALLEL-NEST E-PARALLEL-CALL",
    "wide": "E-WIDE",
    "atomics": "E-ATOMIC E-ATOMIC-MIXED",
    "cooperative": "E-COOP-SHAPE E-COOP-SHARED E-COOP-BARRIER E-COOP-CONFLICT E-COOP-UNORDERED E-COOP-REUSE "
    "E-COOP-UNDECIDED E-COOP-UNWRITTEN E-COOP-GLOBAL E-COOP-WARP E-STAGE-UNREADY E-STAGE-BUSY E-STAGE-LOOP",
    "tasks": "E-SPAWN E-LEASED",
    "rings": "E-PINNED",
    "closures": "E-FN-TYPE E-CLOSURE E-DYN",
    "tests": "E-TEST E-ASSERT-EQ",
    "implementations": "E-IMPL-SIGNATURE E-IMPLEMENTS E-IMPL-EFFECT E-IMPL-NUMERICS E-IMPL-WHEN E-IMPL-USE "
    "E-IMPL-TARGET E-IMPL-CALL E-IMPL-PARAM",
    "printing": "E-PRINT-ARG E-FORMAT-TARGET",
    "layouts": "E-LAYOUT-OVERLAP E-LAYOUT-GAP E-LAYOUT-CONSUMER E-LAYOUT",
    "fragments": "E-FRAGMENT",
    "lends": "E-LENDS",
    "modules": "E-IMPORT E-PRIVATE E-MANGLE",
    "hosts": "E-REQUEST E-SESSION E-SYMBOL E-SITE E-EDIT-PROFILE E-CONTRACT E-SIGNATURE E-DECLARATION "
    "E-EFFECT-EXPANSION E-CALLER-EFFECT E-CONTEXT-CLOSURE E-PRESERVE",
    "migrations": "E-MIGRATION-SCOPE E-MIGRATION",
    "sketches": "E-SKETCH-CHOICES E-SKETCH-EMPTY E-SKETCH-NAME E-SKETCH-SITE E-SKETCH-OVERLAP E-SKETCH-SEALED "
    "E-SKETCH-CONTRACT E-SKETCH-BUDGET",
    "validation": "E-REFERENCE E-TOLERANCE E-TEST-POLICY E-DOMAIN E-VALIDATION",
    "commands": "E-PROJECT-OR-ENVIRONMENT E-TARGET E-TARGET-FEATURE E-TARGET-MISMATCH E-TARGET-TOOLKIT E-DEVICE-CARD E-EXPORT "
    "E-EXPORT-TAMPERED E-EXPORT-TOOLCHAIN E-RULE",
    "harness": "E-HARNESS-MAPPING E-HARNESS-DTYPE E-HARNESS-SYMBOL E-HARNESS-FORMAT",
    "limits": "E-SOURCE-LIMIT E-DEPTH E-AST-LIMIT E-EXPANSION-LIMIT E-EFFECT-LIMIT E-INTERNAL E-PROJECTION "
    "E-RESOURCE-OR-IO",
}
OWNER = {code: name for name, codes in CODES.items() for code in codes.split()}


def every_card() -> dict[str, str]:
    """The language's cards, then the hosts' and the command line's."""
    return CARDS | TOOL_CARDS


def card_of(code: object) -> str | None:
    """The one card that states the rule behind a diagnostic code; None for a code no card owns, such as one a
    recipe's `require` chose."""
    return OWNER.get(code) if isinstance(code, str) else None


def select_cards(source: str, has_views: bool = False, has_records: bool = False, has_sums: bool = False,
                 lends: bool = False) -> dict[str, str]:  # fmt: skip
    # Actual tokens prevent comments/spacing from silently choosing the curriculum.
    tokens = [token.s for token in lex(source)]
    words = set(tokens)
    wanted = {
        "views": has_views or words & {"buffer", "stack", "len"},
        "compact": "compact" in words,
        "scan": "scan" in words,
        "floats": words & {"f32", "f64"},
        "math": words & {"sqrt", "floor", "ceil", "trunc", "abs", "to_bits"},
        "storage": words
        & {"f16", "bf16", "f8e4m3", "f8e5m2", "quantize", "quantize_stochastic", "from_bits", "mma_unordered"},
        "gradients": words & {"grad"},
        "records": has_records,
        "generators": words & {"family", "derive", "recipe"},
        "memory": words & {"buffer", "stack"},
        "sums": has_sums or words & {"match", "try"},
        "generics": words & {"trait", "impl"} or has_generic_brackets(source),
        "owners": words & {"Buf", "Array", "take", "swap", "defer", "linear"},
        "effects": words & {"extern", "unsafe", "pure", "effects"},
        "assembly": "asm" in words,
        "foreign": "launch" in words or {"extern", "implements"} <= words,
        "parallel": words & {"parallel", "reduce", "transfer", "device", "pinned", "unified"},
        "wide": words & {"load_wide", "store_wide", "Cache"},
        "atomics": words & set(ATOMICS),
        "cooperative": words
        & {"barrier", "shuffle", "shuffle_xor", "shuffle_down", "shuffle_up", "warp", "pipeline", *COLLECTIVE_VOTES}
        or {"blocks", "threads"} <= words,
        "tasks": words & {"spawn", "wait", "collect", "Group", "Atomic", "Mutex"},
        "rings": "IoRing" in words,
        "tests": words & {"test", "assert", "assert_eq"},
        "implementations": words & {"implements"},
        "printing": words & {"print", "println", "eprint", "eprintln", "format"},
        "layouts": "layout" in words,
        "fragments": words & {"WmmaA", "WmmaB", "WmmaAcc", "MmaA", "MmaB", "MmaAcc", "TmemAcc"},
        "lends": lends or "lends" in words,  # a record the packet shows lends a view
        "closures": "dyn" in words or closure_or_fn_type(tokens),
        "modules": words & {"module", "import", "pub"},
    }
    return {name: CARDS[name] for name in [*CORE, *(n for n, on in wanted.items() if on)]}


def closure_or_fn_type(tokens: list[str]) -> bool:
    """`(|x:u64| ...` or `, || ...`: a closure, written only as an argument; or `fn(u64) -> u64`, a function type.
    A `|` or `||` after an operand is an operator."""
    return any((a in {"(", ","} and b in {"|", "||"}) or (a, b) == ("fn", "(") for a, b in pairwise(tokens))


def has_generic_brackets(source: str) -> bool:
    """`fn f[T]`, `struct S[T]` or `enum E[T]`: a declaration keyword, a name, then `[`."""
    tokens = [t.s for t in lex(source)]
    return any(a in {"fn", "struct", "enum"} and c == "[" for a, c in zip(tokens, tokens[2:], strict=False))


def program_cards(source: str) -> dict[str, str]:
    """The cards a whole program selects, with views, records and sums found from its own tokens."""
    words = {t.s for t in lex(source)}
    return select_cards(source, bool(words & {"ro", "rw"}), "struct" in words, "enum" in words)


def triggers() -> dict[str, list[str]]:
    """The words that make `select_cards` send each card, found by asking it about every word the cards use."""
    words = {w for text in CARDS.values() for w in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", text)} | {"|", "||"}
    found: dict[str, set[str]] = {}
    for word in words:
        for name in set(select_cards(word)) - set(CORE):
            found.setdefault(name, set()).add(word)
    return {name: sorted(found.get(name, ())) for name in CARDS}


SCHEMA = "cairn.rules/1"
CODE = re.compile(r"E-[A-Z0-9]+(?:-[A-Z0-9]+)*")


def rules(asked: str = "", source: str | None = None) -> dict[str, Any] | None:
    """What `cairn rules` answers, offline: with nothing asked every card and its codes; the card that owns a code; a
    card by name; or, given a program's `source`, the cards it selects beyond the three every program gets. None when
    `asked` is none of these."""
    if source is not None:
        chosen = [name for name in program_cards(source) if name not in CORE]
        return {"schema": SCHEMA, "asked": asked, "always": list(CORE), "cards": [card(name) for name in chosen]}
    if not asked:
        words = triggers()
        return {"schema": SCHEMA, "cards": [{**card(name, text=False), "words": words.get(name, [])}
                                            for name in every_card()]}  # fmt: skip
    if asked in every_card():
        return {"schema": SCHEMA, "asked": asked, "cards": [card(asked)]}
    if owner := card_of(asked):
        return {"schema": SCHEMA, "asked": asked, "code": asked, "cards": [card(owner)]}
    return None


def card(name: str, text: bool = True) -> dict[str, Any]:
    """One card as `cairn rules` gives it: its name, whether it is the language's or a tool's, its codes, its text."""
    said = {"name": name, "kind": "language" if name in CARDS else "tool", "codes": sorted(CODES[name].split())}
    return {**said, "text": every_card()[name]} if text else said
