"""Inspectable guarded C++20 emission. The backend is not verified."""
from __future__ import annotations
from pathlib import Path
from .syntax import *
RUNTIME = (Path(__file__).parent / "runtime/cairn_runtime.hpp").read_text(encoding="utf-8")

class Emitter:
    def __init__(self,p:Program): self.p=p; self.lines=[]; self.ind=0; self.counter=0
    def put(self,s=""): self.lines.append("  "*self.ind+s)
    def name(self,n): return "v_"+n
    def extent(self,t): return t.extent if t.extent.isdigit() else self.name(t.extent)
    def signature(self,f):
        ps=", ".join(t.cpp()+" "+self.name(n) for n,t in f.params)
        return f'extern "C" {f.ret.cpp()} cf_{f.name}({ps}) noexcept'
    def emit(self):
        self.put('// Generated by '+VERSION+'. Do not edit; edit the CAIRN source.')
        self.put('#include "cairn_runtime.hpp"')
        for n,fs in self.p.records.items():
            self.put("struct ct_"+n+" {")
            self.ind+=1
            for f,t in fs: self.put(t.cpp()+" "+self.name(f)+";")
            self.ind-=1; self.put("};")
        for n,vs in self.p.enums.items():
            self.put("enum class ct_"+n+" : std::uint32_t { "+", ".join(self.name(v) for v in vs)+" };")
        for f in self.p.functions: self.put(self.signature(f)+";")
        for f in self.p.functions:
            self.put(); self.put(self.signature(f)+" {"); self.ind+=1
            arrays=[(n,t) for n,t in f.params if t.mode!="value"]
            for n,t in arrays: self.put(f"cr::view({self.name(n)}, {self.extent(t)});")
            for i,(n,t) in enumerate(arrays):
                for m,u in arrays[i+1:]:
                    if t.mode=="rw" or u.mode=="rw":
                        self.put(f"cr::disjoint({self.name(n)}, {self.extent(t)}, {self.name(m)}, {self.extent(u)});")
            for n,t in f.params:
                if t.name in self.p.enums and t.mode=="value":
                    self.put(f"if(static_cast<std::uint32_t>({self.name(n)}) >= {len(self.p.enums[t.name])}) cr::trap();")
            self.block(f.body); self.ind-=1; self.put("}")
        return "\n".join(self.lines)+"\n"
    def block(self,ss):
        for s in ss:
            es=s.exprs
            if s.tag in {"let","reg"}:
                self.put(("const " if s.tag=="let" else "")+s.ty.cpp()+" "+self.name(s.name)+" = "+es[0].cpp+";")
            elif s.tag=="compact":
                out,hi,pred,value = es
                used=self.name(s.name); i=self.name(s.binder)
                self.put(f"std::size_t {used} = 0;")
                self.put(f"for (std::size_t {i}=0; {i}<{hi.cpp}; ++{i}) {{")
                self.ind+=1
                self.put(f"if ({pred.cpp}) {{")
                self.ind+=1
                # The only unchecked store constructor: induction gives used <= i < n.
                # The source cannot mutate used or read output during collection.
                self.put(f"{out.cpp}[{used}] = {value.cpp};")
                self.put(f"++{used};")
                self.ind-=1; self.put("}")
                self.ind-=1; self.put("}")
            elif s.tag=="assign": self.put(es[0].cpp+" = "+es[1].cpp+";")
            elif s.tag=="return": self.put("return"+(" "+es[0].cpp if es else "")+";")
            elif s.tag=="expr": self.put(es[0].cpp+";")
            elif s.tag in {"if","while"}:
                condition = es[0].cpp
                if condition.startswith("(") and condition.endswith(")"):
                    condition = condition[1:-1]
                self.put(s.tag+" ("+condition+") {"); self.ind+=1; self.block(s.body); self.ind-=1
                if s.other:
                    self.put("} else {"); self.ind+=1; self.block(s.other); self.ind-=1
                self.put("}")
            elif s.tag=="for":
                self.counter+=1; lim="cr_limit_"+str(self.counter)
                self.put("{"); self.ind+=1
                # Source order is lower bound, upper bound, then iteration.
                begin="cr_begin_"+str(self.counter)
                self.put(f"const std::size_t {begin} = {es[0].cpp};")
                self.put(f"const std::size_t {lim} = {es[1].cpp};")
                n=self.name(s.name)
                self.put(f"for (std::size_t {n} = {begin}; {n} < {lim}; ++{n}) {{")
                self.ind+=1; self.block(s.body); self.ind-=1; self.put("}")
                self.ind-=1; self.put("}")
