"""`cairn doc`: an API reference taken from the checked program, so it cannot drift from the code.

For every public declaration of a module: its signature with bounds, the comment written above it, and
for a function the effect row the checker inferred. A template's row is the one at its witnesses: what it
may do for any arguments within its bounds, besides what their own trait members do.
"""

from __future__ import annotations

import re

from .agent_tools import generics, local, signature, type_declarations
from .cairnc import Checker, Parser, Program, derive, link, specialize
from .traits import described

TABLES = (("records", "struct"), ("sums", "enum"), ("enums", "enum"), ("traits", "trait"), ("consts", "const"))


def comment_above(text: str, offset: int) -> list[str]:
    """The `//` lines directly above a declaration, as one paragraph (or nothing)."""
    lines = text[:offset].rstrip().split("\n") if offset > 0 else []
    found: list[str] = []
    while lines and lines[-1].lstrip().startswith("//"):
        found.insert(0, lines.pop().lstrip()[2:].strip())
    return [" ".join(found)] if found else []


def document(source: str, modules: list[str] | None = None) -> str:
    c, verdicts, rows = described(lambda: Checker(specialize(derive(link(Parser(source).parse())))))
    p = c.p
    out: list[str] = []
    for module in modules or sorted(m for m in set(p.modules.values()) if m not in p.sources):
        text = p.sources.get(module, source)

        def shown(name: str, module: str = module) -> bool:
            return p.modules.get(name) == module and (name in p.public or not module)

        def above(pattern: str, text: str = text) -> list[str]:
            at = re.search(pattern, text, re.M)
            return comment_above(text, at.start()) if at else []

        out += [f"# {module or 'root module'}", "", *above(rf"^module {re.escape(module)};"), ""]
        for table, kind in TABLES:
            for name in filter(shown, getattr(p, table)):
                one = Program(generics=p.generics, attributes=p.attributes, public=p.public)
                setattr(one, table, {name: getattr(p, table)[name]})
                out += [
                    f"```cairn\n{type_declarations(one)}\n```",
                    *above(rf"^(?:pub )?(?:linear )?{kind} {re.escape(local(name))}\b"),
                    "",
                ]
        for name, recipe in p.recipes.items():
            if shown(name):
                head = f"pub recipe {local(name)}{generics(recipe.statics)}" + (
                    f" for {recipe.param}" if recipe.param else ""
                )
                out += [f"```cairn\n{head}\n```", *comment_above(text, recipe.start), ""]
        for f in [f for f in c.fs.values() if f.module == module and not f.bindings and (f.owner or shown(f.name))]:
            impl = f"impl {f.owner[0]} for {f.owner[1].display()}: " if f.owner else "pub " if module else ""
            row = ", ".join(f"`{x}`" for x in sorted(rows.get(f.name, ()))) or "none"
            certified = verdicts.get(f.name, "ok") == "ok"
            effects = f"Effects{' (any arguments within its bounds)' if f.generics else ''}: {row}." if certified else (
                f"Checked per instance: {verdicts[f.name]}")  # fmt: skip
            out += [f"```cairn\n{impl}{signature(f)}\n```", *comment_above(text, f.start), effects, ""]
    return "\n".join(out).rstrip() + "\n"


def standard_library() -> str:
    """The reference of every packaged module, in one document."""
    from .modules import STD

    names = sorted("std." + path.stem for path in STD.glob("*.cairn"))
    body = document("".join(f"import {m};\n" for m in names) + "fn main() -> i32 { return 0; }\n", names)
    return "<!-- Generated by `cairn doc --std`; edit the comments in src/cairn/std/*.cairn instead. -->\n\n" + body
