" Vim syntax file for CAIRN. Generated by `python -m cairn.editor.grammar`; do not edit.
if exists("b:current_syntax") | finish | endif
syntax case match
syntax iskeyword @,48-57,_,$

syntax keyword cairnConditional else if match
syntax keyword cairnRepeat each for in while
syntax keyword cairnFlow break continue defer return try yield
syntax keyword cairnConcurrency compact parallel reduce spawn
syntax keyword cairnDeclaration const derive enum extern family fn impl import kernel module nat struct trait type where
syntax keyword cairnBinding buffer let reg stack
syntax keyword cairnModifier as dyn linear mut pub pure ro rw unsafe
syntax keyword cairnConstant false true zeroed
syntax keyword cairnType Array Atomic Buf Dyn Group IoRing MmaA MmaAcc MmaB Mutex Ticket TmemAcc WmmaA WmmaAcc WmmaB bf16 bool f16 f32 f64 f8e4m3 f8e5m2 i16 i32 i64 i8 u16 u32 u64 u8 usize void
syntax keyword cairnVariant Empty Err Invalid None Ok Overflow Some
syntax match cairnBuiltin /\v<(abs|add_wrap|asm|assert|assert_eq|ceil|collect|eprint|eprintln|floor|format|from_bits|len|max|min|mma_load|mma_store|mma_unordered|mmio_read|mmio_write|mul_wrap|print|println|quantize|quantize_stochastic|shl_wrap|shr|sqrt|sub_wrap|swap|take|to_bits|transfer|trunc|wait)>\ze\s*[[(]/
syntax match cairnCall /\v<\l\w*\ze\s*\(/
syntax match cairnFunction /\v(<(fn|kernel|test)\s+)@<=\h\w*/
syntax match cairnUserType /\v<\u\w*>/
syntax match cairnConstant /\v<\u[A-Z0-9_]*[A-Z0-9]>/
syntax match cairnEnumMember /\v(<\u\w*\.)@<=\u\w*>/
syntax match cairnSelf /\v<(self|Self)>/
syntax match cairnPlacement /\v\@(host|device|pinned|unified)>/
syntax match cairnContext /\v<(after|block|clobbers|exclusive|fold|fuse|grain|implements|into|lanes|layout|lends|needs|out|per_lane|plan|recipe|require|scan|stage|test|unroll|use|vector|volatile|when)>\ze\s+[[:alnum:]_"$+*&|^-]/
syntax match cairnContext /\v<packed>\ze\s*\{/
syntax match cairnContext /\v<align>\ze\s*\(/
syntax match cairnNumber /\v<(0x\x+|\d+(\.\d+)?([eE][+-]?\d+)?)>/
syntax match cairnMeta /\v\$\h\w*/
syntax match cairnOperator /\v[-+*\/%&|^]\=|\=\>|-\>|\.\./
syntax match cairnEscape /\v\\(x\x{2}|[ntr0\\"'])/ contained
syntax region cairnString start=/"/ skip=/\\./ end=/"/ contains=cairnEscape
syntax region cairnChar start=/'/ skip=/\\./ end=/'/ contains=cairnEscape
syntax keyword cairnEffect contained alloc asm atomic barrier dispatch diverge fence ffi ffi_precondition free gpu_alloc gpu_free indirect_call io join lane local_read local_write lock mmio par read spawn stack_storage transfer trap write zero_init
syntax region cairnEffects matchgroup=cairnModifier start=/\v<effects\s*\(/ end=/)/ contains=cairnEffect
syntax match cairnDiagnostic /\v<E(-[A-Z0-9]+)+>/ contained
syntax region cairnComment start=+//+ end=/$/ contains=cairnDiagnostic,@Spell
syntax sync minlines=50

highlight default link cairnConditional Conditional
highlight default link cairnRepeat Repeat
highlight default link cairnFlow Statement
highlight default link cairnConcurrency Statement
highlight default link cairnDeclaration Keyword
highlight default link cairnBinding StorageClass
highlight default link cairnModifier StorageClass
highlight default link cairnConstant Constant
highlight default link cairnType Type
highlight default link cairnUserType Type
highlight default link cairnVariant Constant
highlight default link cairnEnumMember Constant
highlight default link cairnBuiltin Function
highlight default link cairnFunction Function
highlight default link cairnCall Function
highlight default link cairnSelf Identifier
highlight default link cairnPlacement PreProc
highlight default link cairnContext Keyword
highlight default link cairnNumber Number
highlight default link cairnMeta Special
highlight default link cairnOperator Operator
highlight default link cairnEscape SpecialChar
highlight default link cairnString String
highlight default link cairnChar Character
highlight default link cairnEffect Special
highlight default link cairnDiagnostic SpecialComment
highlight default link cairnComment Comment

let b:current_syntax = "cairn"
