"""`cairn doc`: an API reference taken from the checked program, so it cannot drift from the code.

For every public declaration of a module: its signature with bounds, the comment written above it, and
for a function the effect row the checker inferred. A template's row is the one at its witnesses: what it
may do for any arguments within its bounds, besides what their own trait members do. A module is one
heading, its own comment, and one block of declarations, each under its comment and its row as `//` lines,
so the reference reads like the source it came from.
"""

from __future__ import annotations

import re
import textwrap

from ..agent.projection import comment_above, generics, local, signature, type_declarations
from ..compiler.cairnc import Checker, Parser, Program, derive, link, specialize
from ..compiler.traits import described

TABLES = (("records", "struct"), ("sums", "enum"), ("enums", "enum"), ("traits", "trait"), ("consts", "const"))


WIDTH = 120


def commented(lines: list[str]) -> list[str]:
    """Prose as `//` lines of at most WIDTH columns."""
    return [f"// {line}" for text in lines for line in textwrap.wrap(text, WIDTH - 3)]


def document(source: str, modules: list[str] | None = None) -> str:
    c, verdicts, rows = described(lambda: Checker(specialize(derive(link(Parser(source).parse())))))
    p = c.p
    out: list[str] = []
    for module in modules or sorted(m for m in set(p.modules.values()) if m not in p.sources):
        text = p.sources.get(module, source)

        def shown(name: str, module: str = module) -> bool:
            return p.modules.get(name) == module and (name in p.public or not module)

        def above(pattern: str, text: str = text) -> list[str]:
            at = re.search(pattern, text, re.M)
            return comment_above(text, at.start()) if at else []

        entries: list[list[str]] = []
        for table, kind in TABLES:
            for name in filter(shown, getattr(p, table)):
                one = Program(generics=p.generics, attributes=p.attributes, public=p.public)
                setattr(one, table, {name: getattr(p, table)[name]})
                doc = above(rf"^(?:pub )?(?:linear )?{kind} {re.escape(local(name))}\b")
                entries.append([*commented(doc), type_declarations(one)])
        for name, recipe in p.recipes.items():
            if shown(name):
                head = f"pub recipe {local(name)}{generics(recipe.statics)}" + (
                    f" for {recipe.param}" if recipe.param else ""
                )
                entries.append([*commented(comment_above(text, recipe.start)), head])
        for f in [f for f in c.fs.values() if f.module == module and not f.bindings and (f.owner or shown(f.name))]:
            impl = f"impl {f.owner[0]} for {f.owner[1].display()}: " if f.owner else "pub " if module else ""
            row = ", ".join(sorted(rows.get(f.name, ()))) or "none"
            certified = verdicts.get(f.name, "ok") == "ok"
            effects = f"effects: {row}" if certified else f"checked per instance: {verdicts[f.name]}"
            declared = f"{impl}{signature(f)}"
            if len(declared) + len(effects) + 5 <= WIDTH:  # the row at the end of the line it describes
                entries.append([*commented(comment_above(text, f.start)), f"{declared}  // {effects}"])
            else:
                entries.append([*commented([*comment_above(text, f.start), effects]), declared])
        block = ""  # One-line declarations stack; a blank line sets off every declaration that carries a comment.
        for k, entry in enumerate(entries):
            apart = k > 0 and (len(entry) > 1 or len(entries[k - 1]) > 1)
            block += ("\n\n" if apart else "\n" if k else "") + "\n".join(entry)
        told = above(rf"^module {re.escape(module)};")
        out += [f"# {module or 'root module'}", "", *([*told, ""] if told else [])]
        out += [f"```cairn\n{block}\n```", ""] if entries else []
    note = "A generic function's effects are what it may do for any arguments within its bounds, besides what"
    note += " their own trait members do."
    return "\n".join([note, "", *out] if any(f.generics for f in c.fs.values()) else out).rstrip() + "\n"


def standard_library() -> str:
    """The reference of every packaged module, in one document."""
    from ..compiler.modules import STD

    names = sorted("std." + path.stem for path in STD.glob("*.cairn"))
    body = document("".join(f"import {m};\n" for m in names) + "fn main() -> i32 { return 0; }\n", names)
    return "<!-- Generated by `cairn doc --std`; edit the comments in src/cairn/std/*.cairn instead. -->\n\n" + body
