" CAIRN buffers: two-space indent, `//` comments. Generated by `python -m cairn.editor.grammar`.
if exists("b:did_ftplugin") | finish | endif
let b:did_ftplugin = 1
setlocal expandtab shiftwidth=2 softtabstop=2 commentstring=//\ %s comments=://
let b:undo_ftplugin = "setlocal expandtab< shiftwidth< softtabstop< commentstring< comments<"
