"""Foreign implementations: existing C++ and CUDA a project vendors, built by its own toolchain, and inspected.

A manifest's `[foreign]` table maps a vendored source to the symbols it defines, and an `extern` of the project gives
each symbol its CAIRN signature and effects: `extern "sym" fn f(...) effects(...);` for a C function, and, with
`launch(threads, block)`, a `__global__` kernel that host code launches (compiler/launches.py).

    [foreign]
    "vendor/histogram.cpp" = ["histogram_u32_interleaved"]
    "vendor/stencil.cu" = ["stencil_1d_tiled"]
    "vendor/parallel_gpu.cu" = []

The build compiles each source unchanged: a generated unit includes it, then asserts, for every symbol it defines,
the C++ type the CAIRN declaration passes, so a definition with other parameter or result types does not build. The
unit is compiled by the program's own command line (toolchain.foreign_unit), for the program's device target when it
is CUDA, with the runtime headers on the include path. A source that defines no symbol the program declares is
compiled and inspected, and not linked. verify/foreign.py runs an implementation against its reference and says
what it has.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import replace
from pathlib import Path
from typing import Any

from ..compiler.cairnc import compile_program, write_program
from ..compiler.codegen import Emitter
from ..compiler.tree import Function
from ..perf.device import resources
from .project import Project, ProjectError, digest
from .target import DeviceTarget
from .toolchain import foreign_unit


def cuda(path: str) -> bool:
    return path.endswith(".cu")


def linked_device_code(project: Project) -> bool:
    """Whether a CUDA source the program calls is linked into it, which makes its build a device build."""
    return any(cuda(path) and symbols for path, symbols in project.foreign)


def declarations(project: Project) -> tuple[Emitter, dict[str, Function]]:
    """The program's externs by the symbol each names, and an emitter that spells the C++ type of each."""
    p, c, _ = compile_program(project.source)
    return Emitter(p, c), {f.symbol or f.name.rsplit(".", 1)[-1]: f for f in p.functions if f.extern}


def shown(f: Function) -> str:
    return f"{f.name}({', '.join(f'{n}:{t.display()}' for n, t in f.params)})"


def binding(project: Project, path: str, symbols: tuple[str, ...], g: Emitter, declared: dict[str, Function]) -> str:
    """The unit that compiles one vendored source: the source itself, then one assertion per symbol that it has the
    parameter and result types its CAIRN declaration passes."""
    lines = [f"// Generated by CAIRN: {path} as the project vendors it, and the type each declaration passes.",
             f'#include "{project.root / path}"', "#include <cstddef>", "#include <cstdint>", "#include <type_traits>"]  # fmt: skip
    for symbol in symbols:
        f = declared.get(symbol)
        if f is None:
            raise ProjectError(f"{path} is said to define {symbol}, which no extern of this project declares.")
        want = f"{g.type(f.ret)}({', '.join(g.type(t) for _, t in f.params)})"
        lines += [f"static_assert(std::is_same_v<decltype({symbol}), {want}> ||",
                  f"              std::is_same_v<decltype({symbol}), {want} noexcept>,",
                  f'              "{path} defines {symbol} with other types than {shown(f)} passes");']  # fmt: skip
    return "\n".join(lines) + "\n"


def compile_sources(project: Project, directory: Path, cxx: str, arch: str | None, kind: str,
                    device: DeviceTarget | None, timeout: int) -> tuple[list[str], list[dict[str, Any]]]:  # fmt: skip
    """Every vendored source compiled by the program's own command line: the objects to link, and one record per
    source of its path and hash, the symbols it defines, the command, and whether it built and is linked."""
    if not project.foreign:
        return [], []
    if any(cuda(path) for path, _ in project.foreign) and device is None:
        raise ProjectError("A CUDA source compiles for the program's device target, and this build has none.")
    g, declared = declarations(project)
    objects, records = [], []
    for i, (path, symbols) in enumerate(project.foreign):
        unit = directory / f"foreign_{i}{'.cu' if cuda(path) else '.cpp'}"
        unit.write_text(binding(project, path, symbols, g, declared), encoding="utf-8")
        target = directory / f"foreign_{i}.o"
        line = [*foreign_unit(cxx, arch, kind, device if cuda(path) else None, directory), str(unit), "-o", str(target)]
        done = subprocess.run(line, capture_output=True, text=True, timeout=timeout)
        built = done.returncode == 0
        record: dict[str, Any] = {"path": path, "sha256": digest(project.root / path), "symbols": list(symbols),
                                  "command": line, "status": "native-built" if built else "native-build-failed",
                                  "linked": bool(symbols) and built}  # fmt: skip
        if not built:
            record["stderr"] = done.stderr[-8000:]
        if not symbols:
            record["linked_why_not"] = "the program declares no symbol it defines: compiled and inspected only"
        records.append(record)
        objects += [str(target)] if symbols and built else []
    return objects, records


def host_objects(project: Project, directory: Path, cxx: str, timeout: int = 300) -> list[str]:
    """The project's vendored C++ compiled into `directory` as a library's objects, for a program built outside
    `build`, as validation builds one (verify/validation.py). A CUDA source is left out: such a program runs no
    device code."""
    host = replace(project, foreign=tuple((path, symbols) for path, symbols in project.foreign if not cuda(path)))
    write_program(directory, "runtime.cpp", "")  # the runtime headers a vendored source may include
    objects, records = compile_sources(host, directory, cxx, project.arch, "library", None, timeout)
    if failed := failure(records):
        raise ProjectError(f"A vendored source did not build: {failed.stderr[-2000:]}")
    return objects


def failure(records: list[dict[str, Any]]) -> subprocess.CompletedProcess | None:
    """The first vendored source that did not build, as the build reports a failed step."""
    failed = next((r for r in records if r["status"] != "native-built"), None)
    return subprocess.CompletedProcess(failed["command"], 1, "", failed["stderr"]) if failed else None


def inspect(project: Project, device: DeviceTarget, directory: Path, cxx: str = "g++", timeout: int = 600) -> dict:
    """Each vendored CUDA source compiled for `device` as the build compiles it, to a cubin, with what ptxas reports of
    every kernel in it: registers, spilled bytes, stack and shared memory. Nothing is launched."""
    if not shutil.which("nvcc"):
        return {"status": "not-run", "reason": "nvcc is needed to read a kernel, and it is absent"}
    g, declared = declarations(project)
    found: dict[str, Any] = {}
    for i, (path, symbols) in enumerate(project.foreign):
        if not cuda(path):
            continue
        unit = directory / f"inspect_{i}.cu"
        unit.write_text(binding(project, path, symbols, g, declared), encoding="utf-8")
        cubin = directory / f"inspect_{i}.cubin"
        prefix = [f for f in foreign_unit(cxx, None, "exe", device, directory) if f != "-c"]
        line = [*prefix, "-cubin", "-Xptxas", "-v", str(unit), "-o", str(cubin)]
        done = subprocess.run(line, capture_output=True, text=True, timeout=timeout)
        if done.returncode:
            found[path] = {"status": "compile-failed", "command": line, "stderr": done.stderr[-4000:]}
            continue
        kernels = {}
        for symbol, info in resources(done.stderr + done.stdout).items():
            device.accept(info["arch"], f"ptxas's report of {symbol}")
            kernels[demangled(symbol)] = {k: v for k, v in info.items() if k != "arch"}
        found[path] = {"status": "inspected", "sha256": digest(project.root / path), "command": line,
                       "kernels": kernels}  # fmt: skip
    return {"status": "read", "device_target": device.record(), "sources": found}


def demangled(symbol: str) -> str:
    """A kernel's name as C++ writes it, when CUDA's cu++filt is here; otherwise its symbol."""
    tool = shutil.which("cu++filt")
    if not tool:
        return symbol
    done = subprocess.run([tool, symbol], capture_output=True, text=True, timeout=60)
    return done.stdout.strip() or symbol
